disable-custom-skins: false
disable-custom-capes: true
disable-custom-geometry: true
disable-ingame-skin-change: true
disable-transparent-skins: true
allowed-transparency-percentage: 5
# Recommended minimum percentage: 3
